title: "[Announcement] "
labels: ["announcement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Announcement
        Share important news about bunctl updates, releases, or community events.
  - type: textarea
    id: announcement
    attributes:
      label: Announcement
      description: What would you like to announce?
    validations:
      required: true